### ISSUE TITLE
Key-based authentication

### ISSUE THREAD

**Issue by yngwi** [KenN7/vim-arsync#6]
Hi,
do you plan on adding key-based authentication to the plugin (instead of username/password)? This would be very convenient.
Kind regards,
Daniel

**Comment by KenN7** [comment]
Hi,
key-based auth is already supported due to the fact that the plugin uses rsync in the backend.
You just have to copy your keys to your remote host (using `ssh-copy-id` ) and then comment out the password setting in the .vim-arsync config file like so: 
```
#remote_passwd  secret 
```
(You could also comment out the user setting if your remote host is using the same user as your local one)
 Rsync will automatically fall down to key-based auth.

Cheers,

**Comment by yngwi** [comment]
Great thank you
